# Generated by Django 6.0.7 on 2026-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solar Plant',
                'verbose_name_plural': 'Solar Plants',
                'ordering': ['plant_name'],
            },
        ),
    ]
