# Generated by Django 6.0.7 on 2026-07-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('INVERTER', 'Inverter'), ('METER', 'Energy Meter'), ('BATTERY', 'Battery'), ('WEATHER', 'Weather Station'), ('SENSOR', 'Sensor')], max_length=20)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20)),
                ('installed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.solarplant')),
            ],
            options={
                'ordering': ['device_name'],
            },
        ),
    ]
