# Generated by Django 6.0.7 on 2026-08-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='actual_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='threshold_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
