# Generated by Django 6.0.7 on 2026-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current', models.DecimalField(decimal_places=2, max_digits=5)),
                ('power', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irradiance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'solar_data',
                'managed': False,
            },
        ),
    ]
